[package]
name = "basm-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
basm = { path = "../basm/" }
ahash = { workspace = true }
string-interner = { workspace = true }


[dev-dependencies]
expect-test = { workspace = true }
